/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "stm32f446xx.h"
#include "spi.h"
#include <stdio.h>

char src[] = "Hello World";
char dest[20];

int main(void) {
    uint32_t count = 0;
    GPIO_init();
    SPI1_master();
    SPI3_slave();

    for (count = 0; count < sizeof(src); count++) {
        SPI1->DR = src[count]; // send data from SPI
        while (!(SPI1->SR & (1 << 1))) {
            // wait until TXE (Transmit buffer empty) flag is set
        }
        if (SPI3->SR & (1 << 0)) {
            dest[count] = SPI3->DR; // receive data from SPI
        }
    }

    while (1) {
        // Main loop
    }
}
