/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include<stdio.h>
#include "stm32f446xx.h"
int main(){
RCC->AHB1ENR |= RCC_AHB1ENR_GPIOAEN; // Enable clock for GPIOA
RCC->APB1ENR |= RCC_APB1ENR_TIM2EN;  // Enable clock for Timer 2

GPIOA->MODER &= ~(3UL << (5 * 2));  // Clear mode bits for PA5
GPIOA->MODER |= (2UL << (5 * 2));   // Set PA5 to alternate function mode

GPIOA->AFR[0] &= ~(0xF << (5 * 4)); // Clear AF bits for PA5
GPIOA->AFR[0] |= (1 << (5 * 4));    // Set AF1 for PA5

TIM2->ARR = 999; // Set the auto-reload register value (for example, 999)

TIM2->CCMR1 &= ~TIM_CCMR1_OC1M; // Clear the OC1M bits
TIM2->CCMR1 |= TIM_CCMR1_OC1M_1 | TIM_CCMR1_OC1M_2; // Set PWM mode 1
TIM2->CCMR1 |= TIM_CCMR1_OC1PE; // Enable preload for TIM2->CCR1

TIM2->CCER |= TIM_CCER_CC1E; // Enable the output for channel 1

TIM2->CR1 |= TIM_CR1_CEN; // Start Timer 2

while (1) {
    for (int i = 0; i <= 999; i++) {
        TIM2->CCR1 = i;
        HAL_Delay(10); // Adjust delay for smooth transition
    }
    for (int i = 999; i >= 0; i--) {
        TIM2->CCR1 = i;
        HAL_Delay(10);
    }
}
